### PR TITLE
Prepare for switch to eventgate and support .meta.stream

### PR DESCRIPTION
**Pull request by Pchelolo**
Bug: https://phabricator.wikimedia.org/T226198

### CODE REVIEW

**Comment by Pchelolo** [comment]
The tests are failing for unrelated reason. Investigating now.

**Comment by d00rman** [comment]
From what I can tell, all of the test events now use `stream`. It would be good to have a mix of the two given that we'll be in that situation for a while.

**Comment by Pchelolo** [comment]
> From what I can tell, all of the test events now use `stream`. It would be good to have a mix of the two given that we'll be in that situation for a while.

Ok, makes sense. Reverted in some places, so now it's a fair mix.

**Comment by Pchelolo** [comment]
ok, finally I got travis to pass. We probably need to merge and deploy soon to unblock @ottomata

**Pull request merged**
