### PR TITLE
Switch to new even formats and topics

### PR DESCRIPTION
**Pull request by Pchelolo**
Together with analytics we've changed the event schemas and started producing events to the new topics, so updated CP to use these new updated events so that eventually we could stop producing deprecated events.

cc @wikimedia/services

### CODE REVIEW

**Comment by Pchelolo** [comment]
Corresponding puppet change: https://gerrit.wikimedia.org/r/#/c/308077/

**Comment by d00rman** [comment]
:+1: I'm guessing we have to wait till the end of next week to deploy this?

**Comment by d00rman** [comment]
Let's put this on hold until late next week.

**Comment by Pchelolo** [comment]
> 👍 I'm guessing we have to wait till the end of next week to deploy this?
Why? New events are in prod right now.

**Comment by d00rman** [comment]
> Why? New events are in prod right now.

Let's focus on tranclusions now. If all goes well, we can get this change in a PuppetSWAT window.

**Pull request merged**
