### PR TITLE
Don't reuse request_id

### PR DESCRIPTION
**Pull request by Pchelolo**
Bug: https://phabricator.wikimedia.org/T151934

### CODE REVIEW

**Comment by gwicke** [comment]
:+1: 

@Pchelolo, are there any reasons to not merge this right away?

**Comment by Pchelolo** [comment]
Let's give @d00rman a chance to chip in?

**Comment by gwicke** [comment]
@Pchelolo: Yup, otherwise happy to merge whenever you are ready.

**Comment by d00rman** [comment]
I would honestly prefer setting another header or something similar. Sticking this in `x-triggered-by` with `, reqId:xxx` feels like a work-around IMHO and complicates parsing the field (unnecessarily IMO)

**Comment by gwicke** [comment]
@d00rman, we need to build up a trace of request ids / topics etc, and x-triggered-by is designed to do exactly that, in a list of URLs. Since each subrequest will get a new request id, we will can have multiple `reqid:xxx` URLs in this trace.

**Comment by gwicke** [comment]
@Pchelolo, this needs a rebase.

**Comment by gwicke** [comment]
Did a quick & dirty rebase, lets see if the tests pass.

**Comment by gwicke** [comment]
That clearly did not work.

@d00rman, if you are okay with the approach in principle I can look into doing a proper rebase.

**Comment by d00rman** [comment]
I have soften my position on this so am ok with going with a different reqID for child events.

**Comment by gwicke** [comment]
> I have softened my position on this so am ok with going with a different reqID for child events.

Okay, cool ;) Added a proper rebase to my todo.

**Comment by gwicke** [comment]
Rebased in #203.

**Pull request closed without merging**
