### PR TITLE
Added test for startup offset behaviour

### PR DESCRIPTION
**Pull request by Pchelolo**
No code changes, just a test for https://github.com/d00rman/kafka-node/pull/2

So, the tests should fail until that one is settled.

### CODE REVIEW

**Comment by d00rman** [comment]
Hm, something strange is going on here. The tests still fail even after publishing the new version of wmf-kafka-node. Master [builds just fine](https://travis-ci.org/wikimedia/change-propagation/builds/127911818) with the latest version, though.

**Comment by Pchelolo** [comment]
Ok, I've figured it out why do the tests pass locally but not in travis - the root cause is that locally you don't delete kafka completely, but just delete topics, while in travis it's a new kafka install. @ottomata's fix for automatic offset reset works for some reason only in the former situation, not the latter. 

Investigation is not over, but I'm already lost..

**Comment by d00rman** [comment]
Ah, yes! So, there's a thing in Kafka where deleting a topic doesn't delete its log. So, when create a topic with the same name, Kafka assigns it a log file with the same name, but doesn't truncate it, so you end up with a new topic, but with the old queue as well. So in local tests we need to delete the log directory as well.

**Comment by Pchelolo** [comment]
@d00rman hm.. my observations do not support that. When I delete the topic and recreate it, the reported offsets start with 0 (-1 actually). If old data was still in there, we'd read it again, but we don't.

**Comment by Pchelolo** [comment]
@d00rman right. But the funny thing is - for some reason this test started to fail for me locally now. I did not change anything, but yesterday it was passing, today it fails. magic. Investigating.

**Comment by Pchelolo** [comment]
I have updated the PR with some new code, but it doesn't work. Just published to not loose. We need updates in the kafka client code for this to work.

**Comment by Pchelolo** [comment]
kafka client - 0, Petr - 1. After merging https://github.com/d00rman/kafka-node/pull/3 this should finally begin to work.

**Comment by d00rman** [comment]
@Pchelolo let's also reference v0.1.3 of wmf-kafka-node in `package.json` given that it is a requirement.

**Comment by Pchelolo** [comment]
@d00rman ye, I didn't do it because it wasn't published yet.

**Pull request merged**
